### PR TITLE
Mitigate issue in systemd-hostnamed braking hostnamectl and preventing kubelet to restart

### PR DESCRIPTION
**Pull request by vpnachev**
**How to categorize this PR?**

/area os
/kind enhancement
/os suse-chost

**What this PR does / why we need it**:
Mitigate issue in systemd-hostnamed braking hostnamectl and preventing kubelet to restart
Some versions of SuSE CHost are still affected by https://github.com/systemd/systemd/issues/7082.
The mitigation is suggested here https://github.com/coreos/bugs/issues/2193#issuecomment-337767555

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other use
An issue with old version of systemd preventing the `hostnamectl set-hostname` command to succeed and let kubelet start successfully has been mitigated.
```

### CODE REVIEW

**Review by MrBatschner — COMMENTED** [review]
Just a minor tidbit but shouldn't user/administrator/non-vendor supplied drop-ins end up in `/etc/systemd` instead of `/usr/lib/systemd`?

**Comment by vpnachev** [comment]
To be honest, I am not so fluent with the different systemd directories. I just added the dropin next to the current system definition. 
I will move it now to /etc

**Comment by vpnachev** [comment]
>  I will move it now to /etc

Done.

**Review by MrBatschner — COMMENTED** [review]
Small typo in SYSTEMD but apart from that...
/lgtm

**Review by MrBatschner — APPROVED** [review]

**Pull request merged**
