### PR TITLE
cleanup make test, vendor g/g@v1.10, k/k@v1.17.11

### PR DESCRIPTION
**Pull request by timebertt**
**How to categorize this PR?**

/kind cleanup
/priority normal

**What this PR does / why we need it**:
Already adapts the extension's `Makefile` to the change coming with https://github.com/gardener/gardener/pull/2809.
- `-r` is anyways ignored when specifying packages explicitly
- `./test` doesn't contain any tests, that should be run by `make test` currently, so it just removes it from the command

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```improvement operator
NONE
```

### CODE REVIEW

**Review by vpnachev — APPROVED** [review]
/lgtm

**Comment by rfranzke** [comment]
Do you want to revendor g/g@1.10 with this PR?

**Comment by timebertt** [comment]
Done
/area open-source
/title Cleanup make test, vendor g/g@v1.10, k/k@v1.17.11

**Comment by vpnachev** [comment]
Oops. I just opened another pr #27 to revendor but I will close it.

**Comment by timebertt** [comment]
Oops. Sorry 🙊

**Review by vpnachev — APPROVED** [review]
/lgtm

**Comment by vpnachev** [comment]
@timebertt , the CLA was changed recently and it needs to be re-signed.

**Comment by timebertt** [comment]
Yep, I resigned it, but somehow the CLAassistant still does not like my PR :/

**Review by vpnachev — APPROVED** [review]
/lgtm
/ok-to-test

**Pull request merged**
